spring:
  application:
    name: consumer-notification
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: notification
    password: notification
    listener:
      simple:
        default-requeue-rejected: false

